--Student functionality related data

--Student table
CREATE TABLE MESSAGE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    MESSAGE VARCHAR(30) NOT NULL,
 );

--Student data
INSERT INTO STUDENT (ID, MESSAGE) VALUES (1, 'Pirmas');
INSERT INTO STUDENT (ID, MESSAGE) VALUES (2, 'ANTRAS');
INSERT INTO STUDENT (ID, MESSAGE) VALUES (3, 'TREC');